include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    parameter_assignments: true
    avoid_function_literals_in_foreach_calls: false
    avoid_positional_boolean_parameters: false
    prefer_constructors_over_static_methods: false
    unnecessary_lambdas: true
    prefer_final_locals: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    recursive_getters: true
    prefer_spread_collections: true
    prefer_null_aware_operators: true
    prefer_mixin: true
    prefer_iterable_whereType: true
    prefer_interpolation_to_compose_strings: true
    prefer_initializing_formals: true
    prefer_if_null_operators: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_generic_function_type_aliases: true
    prefer_function_declarations_over_variables: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    prefer_equal_for_default_values: true
    prefer_contains: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_conditional_assignment: true
    prefer_adjacent_string_concatenation: true
    overridden_fields: true
    one_member_abstracts: true
    null_closures: true
    library_names: true
    exhaustive_cases: true
    empty_constructor_bodies: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    camel_case_extensions: true
    avoid_void_async: true
    avoid_unused_constructor_parameters: true
    avoid_returning_this: true
    avoid_returning_null_for_void: true
    avoid_returning_null: true
    avoid_redundant_argument_values: true
    avoid_init_to_null: true
    always_declare_return_types: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    directives_ordering: false
    unrelated_type_equality_checks: true
    close_sinks: true
    cancel_subscriptions: true
    avoid_returning_null_for_future: true
    avoid_empty_else: true

analyzer:
  exclude:
    - lib/injection.iconfig.dart
    - lib/database/database.g.dart
    - lib/bloc/pokemon_list_bloc.freezed.dart
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    parameter_assignments: error
